### ISSUE TITLE
Import the iTunes Reviews

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#10]
I'd like to have many of the reviews that are in iTunes be in the system on the new website. 

To help with this: go to iTunes. In the store. Find The Web Ahead. Click reviews. And sort them by "most recent". It'll look like this:

![itunes 2014-08-06 20-38-09 2014-08-06 20-38-11](https://cloud.githubusercontent.com/assets/108474/3836026/22f8fb10-1dcb-11e4-81ef-de30b0004249.jpg)

I already put in all the (good) reviews from 2014. And I did 2 from Jan 2013. We need the rest from 2013. Everything (good) from 2012. And everything (good) from 2011 — except for the 3 that are already in the system. Sorry I didn't strictly go in order. UPDATE: I only added reviews from the _U.S._ store, as Ross so helpfully pointed out below. Oh right, each country has separate reviews! 

You can quickly see what's already there by reading them in chronological order at http://dev-webahead.gotpantheon.com/reviews

Sadly, there is no way to cut and paste. They have to be typed up! So only do this task if you are a good typist, or you want practice in becoming a good typist! :P 

Skip all the negative reviews. And skip any positive reviews that just seem spammy or kinda lame. "Great show! Thumbs up!" I deeply appreciate that people have taken the time to write anything, they just aren't as useful on the new website. 

And feel free to lightly edit them. Fix spelling and grammar.

These reviews will help us get new sponsors! So thanks in advance for all the typing.

**Comment by alyssais** [comment]
@jensimmons the image in the issue description doesn't seem to be working. Maybe try re-uploading?
EDIT: image now works. Might just have been my dodgy internet connection.

**Comment by alyssais** [comment]
I'm pretty sure reviews are per-country as well, so this task is enormous. I could have a go at automating it if that's okay with you…

**Comment by jensimmons** [comment]
Ah, right. There _are_ different reviews in different countries. Gosh it'd be fascinating to see what people are saying on other places. I have switch stores a few times to check, but not often. 

Automate it? That'd be awesome! If you scrape everything into a CVS file I can suck it in. Or into a RSS feed... Drupal has the module called Feeds that allows you to suck content in fairly easily. It's scraping it off the iTunes store that seems the harder piece.

**Comment by jensimmons** [comment]
It might be great to get a few of the best non-English reviews (just a few), but there's no need to grab "all" of the reviews from every country in every language. At least not until we start translating transcriptions into other languages and set this site up as a multi-language website! Let's start with just English. There's no need to have thousands of reviews. A few hundred that's a good sample will work just as well.

**Comment by alyssais** [comment]
I wrote a little [Ruby script](https://gist.github.com/penman/672c529767dbb593f702) that grabs all the reviews and outputs them as CSV. I haven't figured out how to trick iTunes into thinking I'm in a different country yet, but I have [all the UK reviews](https://gist.github.com/penman/b24dbe4e0b45d4594b77).

If you want I could add filtering by rating or something so we only get the good reviews, and it would be good if people from other parts of the world could run the script so we could get all the non-UK reviews.

To run the script use `ruby webahead.rb`. If you're using a Mac then `ruby webahead.rb | pbcopy` will copy the CSV to your clipboard.

**Comment by jensimmons** [comment]
Awesome!

There's info on how to change stores here:
http://support.apple.com/kb/HT6119?viewlocale=en_US&locale=en_US
and
http://support.apple.com/kb/TS5375

Be sure to read all the warnings before you do it. And I don't recommend doing it more than twice (switch and switch back). I'm guessing Apple's got bots in place to ban someone who's changing stores multiple times in a row. Might be a good idea to not do it at all. All the stuff we've bought, our music libraries, access to movies — there's a lot at risk that could get borked. 

I'll try out running this script here in the U.S. and let know you how it goes. This is cool! I'll also work on importing the CSVs into Drupal. I'll let you know if any adjustments need to be made. — Oh, in fact **don't switch stores until after I've succeeded in importing the data**. If we need to make adjustments to the script, let's do that before we go virtually globe trotting.

**Comment by mattsugihara** [comment]
If you wanna just pass that script off, I be happy to run it here in the US

**Comment by mattsugihara** [comment]
Sorry, just actually read the post and saw you linked to it and Jen's already on it. Cheers!

**Comment by jensimmons** [comment]
Actually I haven't run it yet. I want to, but have been focusing on other things that are closer to Minimum Shippable Product. So feel free!

**Comment by jensimmons** [comment]
I might do this eventually, but tabling for now. Thanks Ross for working on it!
