### ISSUE TITLE
Setup the Upcoming Show Calendar properly

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#11]
I started creating a block with a calendar of Upcoming Shows. The content type is all setup. And there's plenty of content in the system. I've created three Views that are all displayed (temporarily) on this page: http://dev-webahead.gotpantheon.com/upcoming-shows

1) The page view that's the longest list — of teaser nodes. 
2) A block that's visible at the bottom of the page that just lists fields: title and date. 
3) A broken Calendar block that's not visible because I didn't finish setting it up. There's a lot of detailed bits of the View that I just skipped over. Argument bits and all. That. Fix that. Make the Calendar work. Something simple. Expected. A calendar that shows the upcoming shows. 

Let me know in this thread if you don't have enough Drupal superpowers yet. I'll add permissions to your role.

**Comment by sffitzpatrick** [comment]
Jen, for stuff like this, should we work on your dev site or create our own instance and maybe use Features to deliver?

I can try to start on this tonight, but I'm not going to assign it to myself yet in case someone else wants to grab it first :)

Sean

**Comment by jensimmons** [comment]
You can work on this directly on dev. I know it's a bit of a risk, but I tend to work fast & dirty most of the time. I am backing up the database several times a day. Just, of course, be careful about not deleting working Views. Feel free to start new ones. If you do want a copy of the current db, let me know. I can Dropbox it to you? Or email? Or hey, we could install Backup & Migrate (I forgot about that module, Pantheon's spoiled me). 

Meanwhile, you and I are the only two people who have privs to do anything beyond adding and editing content. No one else can see Views or Modules or Config, etc. I bet more Drupal devs will join us, but as of Thursday, it's just you and me so far — thus the desire to work fast, even if it's a bit messy.

Eventually we can put things in Features. Later once the site is live, everything new will have to be Featurized. But at this stage, the very beginning of a site, I prefer to not use Features. It slows things down. Make sense? Especially for something this simple — it's just a bitty Calendar. Thanks for asking, though. 

That said, if you succeed in something complex and _want_ to put it in a Feature to get it into Git and not have it accidentally deleted by someone else, we can do that. We'll just have to get you all setup with code access and all. (Another reason to hold off a bit & just cowboy it on dev. No need to clone.)

**Comment by sffitzpatrick** [comment]
I got a basic calendar working as a block and also added a calendar page (http://dev-webahead.gotpantheon.com/upcoming-shows/calendar) before I realized you were using that block... 

I added the date field and was going to create a new date format to show time only but I don't have permission to do that. 

I think something's up with a new release of Calendar or Date because the header now shows the full date (e.g., August 1, 2014). I just noticed this is also happening on some other sites I updated this morning so I'll take a look and see what I can find out!

**Comment by sffitzpatrick** [comment]
OK, turns out the fix for the header thing is in the current alpha release of Date: https://www.drupal.org/node/2313405

**Comment by jensimmons** [comment]
Sean, I gave you date privs. Sorry you didn't have them before. I also just defined three new date formats: short, med & long dates without any time. Those will be handy. @sffitzpatrick

**Comment by jensimmons** [comment]
Yay for awesome calendars!

I installed Date 7.x-2.9-alpha, and the bug is still there. This, right? 
![upcoming shows page the web ahead 2014-08-10 17-38-39 2014-08-10 17-39-09](https://cloud.githubusercontent.com/assets/108474/3870626/caf03a0a-20d6-11e4-9215-72f86ee52516.jpg)

Hm. 

I created a Time-only format, and set that up. And I removed the redundant list-of-upcoming-shows block that was there. (I'd only placed it temporarily so we could see all three views in one place and change them while thinking about all three. Now that they are done, the text list is just living on the home page.)

There's a bit more to do with all this (especially theming), but the calendar is looking great. So I'm happy. :) And I'm going to close this issue. 

Thanks Sean!

**Comment by sffitzpatrick** [comment]
Jen, Yeah that screenshot shows the bug I was talking about. It's kinda crazy--after installing the alpha you have to go to a settings page (/admin/config/regional/date-time/date-views) and click "save" to enable fix the date config. I guess that config page is brand new and you have to manually set the defaults.

I don't think I have access to the date stuff yet (maybe Pantheon caching?) or else I'd try to fix it...

**Comment by jensimmons** [comment]
A ha! That totally did it. 
THANKS!

Yeah, they should have written an update hook.... oh well. I'm glad you knew what was needed.
