### ISSUE TITLE
[Drupal Notes (for the curious)]

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#13]
I thought I'd list a few things about how I Do Drupal.

Pantheon for hosting. Which means there's a dev, test, and live server already all setup. Everything's in Git. If you need access to Drupal, send me your Pantheon account info. You can get a free account if you don't have one already. https://www.getpantheon.com

I use these modules. On. Every. Project. They are rare, but really awesome. You don't need to go figure these out... I just thought I'd mention them. If you start to run into something unusual and don't understand what I'm doing with these, ask. I'm happy to explain:
- Nodeblock
- Empty Page
- Rabbit Hole
- Corresponding Node References
- Fences
- HTML5 Tools
- Insert
- Automatic nodetitles
- 404 Navigation

Also I use:
- Workbench
- and maybe Media (although I'm debating) (UPDATE: nope)
- Logintoboggan
- Picture & Breakpoints (only because Picture requires it)

And along the Religious Debates I say:
- Yes to Features
- No to Panels
- Yes to Context
- No to Blocks

Once things are fully setup, I basically never use core Block interface tools. ALL blocks are created from Node and Views. I _never_ create a Block using the basic core Block tools. Use the Content Block content type instead.  

Base Theme:
- Zen 5

**Comment by jensimmons** [comment]
I just disabled Fences. And replaced it with Display Suite. Kind of revolutionary. Maybe I'll make a screencast later. Meanwhile, wow, it's so much faster to get to clean markup. Yay!

**Comment by chipcullen** [comment]
Interesting selection of modules. I don't know if this is an interesting idea for you or not, but I have something like this I keep lying around:

https://gist.github.com/chipcullen/4118091

Which is basically one big `drush dl` command with my go-to modules in it.

**Comment by jensimmons** [comment]
Nice. That's way faster than creating a custom install profile!
