### ISSUE TITLE
Add content to your user profile. And give me feedback on how you like the form.

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#14]
I just added more fields to the user profiles — so you can now add a bio & some links (like to your website, Twitter, etc). 

So go add that stuff! I want to be able to show you off. 

And then come back here and tell me what else you want / don't want. And what you think of the order of the form fields. (It super easy to rearrange the order of the fields on the form.)

**Comment by PhilJinAus** [comment]
Done :) Maybe add location settings so people can show where in this big wide world we're all from? Other than that, I think it works well as an out of the box drupal form!

**Comment by jensimmons** [comment]
Ooo that's a great idea. Drupal totally has that already built too. It's running the map on http://drupal.org. I/we just have to set it up.

**Comment by jensimmons** [comment]
I just redid the form to make it better. 
http://monosnap.com/image/C71CyZq4QNvjUEMuEa83bkrr8q628B.png

I'll do more in the future, but for now, I think this form is a big improvement. (Thanks Display Suite!)

**Comment by jensimmons** [comment]
I'm going to close this for now. I have big plans for user profiles for later... but want to focus on minimum shippable. And ship!
