### ISSUE TITLE
Is your account detecting your timezone automatically now? How's that going?

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#15]
Drupal supports having users in many different timezones. It'll recalculate all the times for you to be in your timezone — but only if you tell it what your timezone is. 

You can specify your timezone in your user account. But come on, how many people will do that? Enter Timezone Detect. 

I just turned this on (Thu Aug 7, 4:39pm EDT). It should use a js library and Geolocation API to detect where you are and set the Timezone for you. It'll only do this once, not every time you move around. It likely will owkr with new accounts. But I'm not sure if it'll go back and set the timezones for all of you that already have accounts, but didn't set your timezone manually. 

Can you see what's happening for you, and report it here? Especially those of you not in EDT. 

Does the browser ask permission to use Geolocation API? Only when you edit your profile? Or when you hit any page of the site? Did it work? Did your timezone change? (If you didn't set it manually, the system would have defaulted to New York). 

Does it seem like a good / simple experience? Or is it being creepy?

**Comment by fonorobert** [comment]
Only works when logged in. The site doesn't ask to use the geolocation API and when I'm not logged in it displays the original times. I set the timezone on my profile and when I log in it calculates to my local times.

**Comment by jensimmons** [comment]
So timezones are working for you. Did you set your own timezone manually yesterday (or earlier today)? The thing I want to test, that I set up an hour ago, is a new module that gets Drupal to detect people's timezone automatically when they first make their account, so if they don't set it manually, it's done it's best job to guess. 

That's the part I'm not sure of. Sorry if I didn't explain myself very well.

**Comment by mattsugihara** [comment]
huh, I think I'm seeing something different.

Having:
- Already created an account and having login persist
- been unsure of the scope of the time field in my profile, left it on the default (EDT) setting
- Timezone Detect enabled
- Opened a tab and loaded the homepage

I see that I am logged in.
I am not prompted to give the site access to my location.

Going to my account, I see that the time zone field in my account is still EDT and has not changed to PDT and that I am not prompted to go give location permissions.

![geoloc](https://cloud.githubusercontent.com/assets/166028/3849830/6d557b2c-1e7d-11e4-99db-0bd9e324bb73.png)

Hope that helps

**Comment by jensimmons** [comment]
Thanks. Hey can one of you make a new account (from a non-EDT timezone). Let's see if it works with a brand-new account. (Use a different email. And I'll delete the account later.)

**Comment by mattsugihara** [comment]
ok, put in a request

**Comment by jensimmons** [comment]
Cool. Sorry to take so long to approve it. Email notification take a while....

**Comment by jensimmons** [comment]
The timezone is set to "-None selected-". That means this isn't working. Hm. Or maybe — actually I bet you have to log-in @mtsugi, and it will set then?

**Comment by mattsugihara** [comment]
When I created an account and logged in for the very first time it defaulted to EDT, so I'd guess that original setting is overwriting everything?

I tried logging out and logging in again on my primary account (having requested a new password because passwords), and it was still set to EDT and I did not get a permissions request for location.

Also, my upstream spam filters seemed to have caught that request for an account to that test account, so I created a new request with a different email address that I have a bit more control over.

**Comment by mattsugihara** [comment]
Ok, looks good for new accounts. Going to the address in the account creation confirmation email took me directly to my account page, where the local time was set to PDT. It did not ask for location permissions, which makes it less creepy, GeoIP is accurate enough to set a timezone.

Like @fonorobert says, it does not update times for unauthenticated users. Those still show up in EDT.
