### ISSUE TITLE
Make all the feeds work, happy podcast feeds

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#16]
For the most part, people will subscribe to the show using the main iTunes-happy feed. I'm creating such a feed at /feed. We should make sure it works and fully conforms to Apple's standards. You can take a look (in Chrome) at the current feed for the show at: http://feeds.5by5.tv/webahead. 

Also Drupal is making a few feeds by default (through it's defaults for handling taxonomy pages), and I think they could be handy. Here's one (see the icon at the bottom of this page):
http://dev.thewebahead.net/topics/design

I could see where someone might want to subscribe to just all episodes about Design, and not the whole show.

The goal of this task is to make sure all the feeds are well-formed RSS2.0 feeds with media enclosures. 

If we don't get to the extra feeds, or it's not working easily / taking too long, then we can just hide these RSS icons and ship this later (or never). It's a maybe-nice-to-have, it's not a priority. 

Making sure the main feed does conform and work is a high priority.

**Comment by proko** [comment]
Hi Jen. I don't think this can be done just with the built in RSS functionality. We wil probably need [Views RSS](https://www.drupal.org/project/views_rss) and the [iTunes Elements](https://www.drupal.org/project/views_rss_itunes) for this job. I'd be happy to have a look if you approve the use of the modules.

**Comment by jensimmons** [comment]
Yes, both modules are already installed and half configured. Oh, looking this morning I see I was working on this locally the other day, but didn't finish it. Let me wrap up what I was doing:

I started adding the info for iTunes — where is that tutorial that I started to follow?... Ah, here: https://www.drupal.org/node/1346496 I think. Yes, I was working my way through the several pages of https://www.drupal.org/node/1344136. Also this: https://www.drupal.org/node/1473728. And, overall, we want to mimic this: http://feeds.5by5.tv/webahead

Oh, and look a not-saved View I was building locally. Dang, I meant for that to be on the dev server. Let me go move that. Alrighty, the half-done Feed is now at http://dev.thewebahead.net/admin/structure/views/view/podcast_feed/edit

Oh, and right.... I set-up a subdomain to store the main giant logo image... and didn't go back to finish that after the DNS resolved... Ok. Just completed that task now. So there's an image at: http://extras.thewebahead.net/logos/cover.jpg that we can tell the iTunes feed all about. (It's the same image that's at http://icebox.5by5.tv/images/broadcasts/26/cover.jpg)

Oh, one more thing, I created several "iTunes"-named fields for the Epsiode content type, but I want to delete them & not use them. Instead the "description" field, and the "teaser" field should do the trick. We can map it like this:
- description > iTunes summary
- teaser > iTunes subtitle
  while meanwhile having flexible fields that can be used around the website in other places. Instead of creating fields that are named in a way that makes them seem like they only have one purpose. 

Make sense?

_Feel free to ask questions here!!_

I'm not going to have time to work on this over the next two weeks, so feel free to go for it! (I _do_ have time to answer questions.) If there's not much progress on this by Sept 15, then I can jump back in and finish it up.
