### ISSUE TITLE
CHECK IT OUT! We have TOPICS!

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#17]
http://dev-webahead.gotpantheon.com/dev-ops-performance

This is a big reason I wanted to build a website. So people can find all the shows about a certain topic — and can get started by listening to a handful of shows instead of just one. 

I'm only about half-way through the library of episodes, making sure they are each in the right topics — but enough is done to start to see how this is going to work. Now just imagine this page looking beautiful. Maybe having an image for each show (like the guest? Or an _image_ for each show??)

Fabulous.

Take a look and let me know what you think. I'm expecting to need to adjust the list of topics, and what shows go under which topics. It's hard to decide, actually how to organize everything. But it's also very exciting!!

**Comment by jensimmons** [comment]
Ah, and this is why I was asking about "HTML5" on Twitter. 
http://dev-webahead.gotpantheon.com/html5

I was debating whether or not to even have the term. But now I'm figuring, sure, include it. And then use it properly. Maybe then people will learn a bit better what it actually means. It means that stuff!!

Also, I'm not sure where else to put a lot of those shows if I don't have an "HTML5" topic. 

/cc @penman @fonorobert

**Comment by jensimmons** [comment]
Oh, maybe instead of HTML5, it should be "web standards specifications" — or, er, something not so nerdy but that means the same thing. Like something that could also classify Web Payments (which is not part of HTML5, it's post HTML5). 

I keep debating about having a "Process" topic. Seems like half the shows are about that (or more). But then again... maybe it is needed.

**Comment by alyssais** [comment]
I like the idea of calling it "web standards" or something. I don't think "HTML5" is really a sustainable term. A "Process" topic would also be good, I think.

**Comment by fonorobert** [comment]
I like "web standards" or maybe "emerging standards" to suggest it's the new stuff.

**Comment by jensimmons** [comment]
Ooo, I like "emerging standards". I'm going to change it to that. (It's trivial to keep changing these names. And not too hard to make new ones  / reassign things. Yay Drupal.)

**Comment by jensimmons** [comment]
Ok, I finished going through all the shows and assigning them topics. I feel like this is a work-in-progress, finding the right names for the "topics", (even changing "topics" to something better), figuring out which show goes into which topic. Making sure that each topic has the right set of shows, not too many & not too few... it's something that will never be done. It'll always be evolving. But also, I bet it could be better now / better before launch. So I'm totally open to ideas. 

The goal is to give people who've listened to one show an easier way to listen to more than one. Or to give someone who's a big fan of the show a way to introduce their friends or colleagues to the show — instead of saying, "hey go listen to these 80 shows", they can say "go listen to these 6 shows about ___". A shorter list is more doable.

So suggest away. What topics are missing? What shows are not in lists they should be, or are in lists they shouldn't be? What makes for real nice sets, and what seems weird? Anything....

**Comment by Zearin** [comment]
Loving this project.  Keep it up, @jensimmons! :D

Topic idea brainstorm:
- best practices
- new practices
- web standards
- web beauty

Also, several existing topics are design-related.  Would you consider having an umbrella topic “Design” and using nested lists to contain the sub-topics?  

(If so, consider the same for other topics.  “Design” is just the most obvious umbrella topic to my eyes.)

**Comment by jensimmons** [comment]
Thanks, Tony. 

I like your brainstorming list there. Yes, these could use more refinement. Luckily Drupal makes it insanely easy to add more Topics, adjust which shows are in which topic, etc. I have a feeling once I start creating a visual design for these pages it'll become clearer what to do. 

I did think about having a design umbrella topic — and breaking design into several smaller topics. Especially when I had even _more_ shows marked "design". I should probably revisit this again. I almost want to put every show in design — since I think designers should listen to every show and put what they learn into their designs.... ha. It's not clear black & white. Everything's a shade of a grey gradient.

**Comment by jensimmons** [comment]
The word "TOPIC" is starting to drive me crazy. It's not going to make the cut — it's too [wrong]. 

Category? So 2002.
Subject? Maybe. But feels like an elementary school library. 
Hm. I should go poke around Lynda.com and all the zillion book publishers, online tutorial websites to see what words folks are using to separate out 'content' by 'subject matter' — in 2014, in the tech world...

We have to replace the word "Topic". Which, btw, started out as "Genre".

**Comment by proko** [comment]
What about "Areas"? I'm not a native English speaker but "Areas" sounds nice to me. In my mind it's related to investigation, experimental, innovation, discussion-debate etc which are quite web-aheady. 

A quite different approach would maybe be to just use tags.

**Comment by JasonNeel** [comment]
Concepts?
