### ISSUE TITLE
List of Transcript Contributions Block broken —  Views Argument not working

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#18]
Hm. I've built a block at:
http://dev-webahead.gotpantheon.com/admin/structure/views/view/list_of_transcripts/edit/block_1
where a list of transcripts that have been worked on by a particular user should be made.

If you put '30' in the preview box (Jenn's number), you'll see the list of transcripts Jenn worked on. Excellent. (This is relying on a field in the Transcript content type which user references users). 

I dropped that block on the user profile page using a Context. (Which works, I tested using the Made with Drupal box and it's fine). But this block doesn't actually show up on the user's page:
http://dev-webahead.gotpantheon.com/member/jenn-schlick
We should see that same list of transcripts there. 

Dang.

I think the UID argument is not getting properly passed from the user page to the block contextual filter. And I don't know why. I messed around with adding a relationship, but nothing I tried worked. I'm too rusty... I have a vague memory that Views with User Reference arguments is tricker than Views with Node Reference arguments, but it's been a few years since I've done this, and I'm stuck.

Thoughts, @sffitzpatrick? Or any other Drupal devs?

**Comment by sffitzpatrick** [comment]
Jen,  you should be able to pass the UID from the URL. See screenshot: 
![screen shot 2014-08-11 at 2 05 53 pm](https://cloud.githubusercontent.com/assets/807833/3881103/b4b9788c-218a-11e4-95d4-a22cf2599b70.png)

**Comment by jensimmons** [comment]
Ah, excellent! Now we have lists of transcripts. 
![jenn schlick the web ahead 2014-08-11 15-47-27 2014-08-11 15-47-29](https://cloud.githubusercontent.com/assets/108474/3881739/622cc302-2190-11e4-856a-67ddf55e3411.jpg)

Thanks Sean.
