### ISSUE TITLE
Add Chosen on node form select/multiselect fields?

### ISSUE THREAD

**Issue by sffitzpatrick** [jensimmons/thewebahead#19]
I think [Chosen](http://harvesthq.github.io/chosen/) would be a nice enhancement for the long select fields in the admin node forms. For example, the Episode reference on the Sponsor add/edit form. Chosen will make it a lot easier to find episodes AND see what's already selected.

I've done this via form_alter functions but it looks like there's a module :) https://www.drupal.org/project/chosen.

**Comment by jensimmons** [comment]
Great idea. Yes.

I got this half installed. But it's not working. (Ah, Drupal). 

Module installed & on. Should work automatically. Config at http://dev-webahead.gotpantheon.com/admin/config/user-interface/chosen

Library in the repo. at sites/libraries/chosen/chosen/*
See:
![page tpl php - the web ahead 2014-08-12 17-40-31 2014-08-12 17-40-33](https://cloud.githubusercontent.com/assets/108474/3898189/7b2ad1f8-2269-11e4-8823-ffedb6aa2241.jpg)
as per the instructions in their video. I also briefly tried it at sites/libraries/chosen/\* which didn't work either.

The Chosen module used to have a jQuery Update dependency. Not anymore. jQuery update is _off_. That should be fine. 

Caches cleared multiple times. Nada. I've edited the content types, changing the widgets on some of these fields. Nada.

**Comment by sffitzpatrick** [comment]
Huh, it looks like the module is trying but failing to load the plugin at http://dev-webahead.gotpantheon.com/sites/all/libraries/chosen/chosen.jquery.min.js

![screen shot 2014-08-12 at 4 52 32 pm](https://cloud.githubusercontent.com/assets/807833/3898358/2b0a94f4-226b-11e4-851a-383d5d3d6504.png)

But you said you tried that location already!? Is your libraries directory in "all" or directly under "sites"? From the screenshot it looks like libraries in in the right place but you said you tried "sites/libraries/chosen/*" 

I'd be happy to hack on that a bit if I have access to the code (do i?)

**Comment by jensimmons** [comment]
Looks like it does want it to be up one level. Not surprising, that's not what their video said... might have changed. Let me try that now. 

You don't have access to code. Do you have a Pantheon account? What's your username?

**Comment by jensimmons** [comment]
There we go! Works now.

I had tried it a level up, but I also think I perhaps had the wrong files then... meh. Sorry I didn't figure this out earlier. 

This is a great module.
