### ISSUE TITLE
Port the transcripts into the new site

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#2]
I've moved over a lot of the existing transcripts, but only through ep65. There are 8 more that need to be moved. (66, 69, 72, 73, 74, 75, 76, and 77).

You can see a list of existing transcripts at:
http://dev-webahead.gotpantheon.com/admin/workbench/content/all?title=&type=transcript&published=1&items_per_page=100

To create a new transcript, click "Add content". Then "transcript".

![add content the web ahead 2014-08-05 20-04-59 2014-08-05 20-05-25](https://cloud.githubusercontent.com/assets/108474/3820751/6c59cb32-1cfd-11e4-9d00-d00c84cb5e2a.jpg)

Then fill out the form!

Oh — it's WAY EASIER to cut and paste from the original Jekyll transcript files at https://github.com/jensimmons/webahead-transcripts/tree/master/_posts/transcripts than from anyplace else. Ignore the header at the top, move the credit footer to the Credit field, and paste everything else into the transcript field. 

Do go track down who worked on each transcript and credit them please. We've been writing thanks to people who've paid for professional transcriptions, but haven't been crediting all the hard work of all the volunteer transcription. Let's fix that! If that's you, give yourself credit. If you aren't sure who did the transcription, and there's no existing footer, then go look in the git commit history.

![create transcript the web ahead 2014-08-05 20-12-37 2014-08-05 20-12-39](https://cloud.githubusercontent.com/assets/108474/3820803/6a0741ce-1cfe-11e4-9a81-9b17ad074e81.jpg)

I've written further instructions in the help text for the form, but, as with everything, please let me know if anything is at all confusing. I can adjust Drupal to make it easier — I just have to know that I should.

**Comment by jensimmons** [comment]
I just added a second field for giving credit to the person who did the transcription. 

![edit transcript transcript for accessibility with dale cruse the web ahead 2014-08-05 20-52-52 2014-08-05 20-52-54](https://cloud.githubusercontent.com/assets/108474/3821087/2afbe3da-1d04-11e4-900e-c189306d9eac.jpg)

It makes adding a transcription messier (sorry), but it gives us really great data — basically making it possible to list all the transcriptions someone's worked on on their user profile page. Which I think is cool.

**Comment by jlschlick** [comment]
This is done.

**Comment by jensimmons** [comment]
WoooooooHOoooooooooo!!!!!!!!!
