### ISSUE TITLE
Test the newsletter signup

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#22]
I'm creating a mailing list at Mailchimp for sending newsletters. I've setup Drupal & Mailchimp so that they talk to each other. 

It'd be a help to me if you'd go signup for the newsletter at http://dev-webahead.gotpantheon.com/newsletter/signup as a test to see if all the plumbing works. You can always unsubscribe whenever you want.

**Comment by JasonNeel** [comment]
Jen, I tried to but got an access denied page. 
![image](https://cloud.githubusercontent.com/assets/1549704/3945631/abbbf974-264b-11e4-9d18-ed8105c4f6e6.jpg)

**Comment by jensimmons** [comment]
A ha! I need to change Drupal permissions. Which I've now done. 

Try again?

**Comment by JasonNeel** [comment]
Yep! That works!

**Comment by jensimmons** [comment]
It did work! I see your email on the list. Excellent.
