### ISSUE TITLE
Transcripts: Wrap sponsor reads in an <aside> 

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#25]
Here's a fairly simple task that'll just require some time and attention to detail.

I want to style the sponsor reads in the transcripts a bit differently from the rest of the transcript. Which requires wrapping each read in an aside element. Like this:

`<aside class="sponsor-break"><dt>Jen</dt>`
`<dd><p>Stuff I say about the sponsor</p>`
       `<p>More stuff I'm saying</p>`
`</dd>`
`</aside>`

The dt, dd, p elements are all there. You will likely need to end the dd from the discussion just before the sponsor read, and add a dt with my name & all at the very begging in of the read..... You can look at one of the ones that are already done to see how I didi it. 

I just put this code into the transcripts for 80-85. Plus 65. All the rest still need to be done. 

It can be a bit finicky. Look at the page after you've saved & see if it worked. If not, edit the markup. Perhaps removing extras carriage returns... until it works. 

Right now it'll look like this when done: 

![the complexity and the humanity with trent walton the web ahead 2014-10-02 00-54-54](https://cloud.githubusercontent.com/assets/108474/4486942/534fd238-49f0-11e4-9304-e2af58481d6a.png)

I'm sure I'll polish up the styling more later.

**Comment by jensimmons** [comment]
Oh, also, make these changes at: http://dev.thewebahead.net. That's where everything is happening these days. 

You can log in at http://dev.thewebahead.net/user.

**Comment by JasonNeel** [comment]
I was able to sit down last night and run through the remaining transcripts looking for sponsor breaks. I think I got them all?

**Comment by jensimmons** [comment]
This is super awesome! Thank you Jason.

**Comment by jensimmons** [comment]
Oh, I think we need to update the last three — ep 86, 87, 88.

**Comment by JasonNeel** [comment]
Got ‘em.

**Comment by jensimmons** [comment]
Yay! Thanks :) 

I just need to style them, now. Now that the rest of the episode page is almost done.
