### ISSUE TITLE
Preprocess function needed

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#26]
So I think I need to change the page layout for an episode based on whether or not there's a transcript for that episode. I'm thinking — create a preprocess function on the episode node type where it tests to see if the node-reference field referencing the associated transcript (a separate content type) is empty or not. If it's empty, I want to put a class in the body element of "no-transcript". Then I can do whatever with the page layout. 

Anyone want to track down what that preprocess function should be? I haven't written such a function based on a field before (and I'm currently at a conference with super crappy internet, so I can't easily look around.)

**Comment by sffitzpatrick** [comment]
Jen, I've been so out of touch lately! Lots of traveling. You would use [template_preprocess_field](https://api.drupal.org/api/drupal/modules%21field%21field.module/function/template_preprocess_field/7) for this.

We'd probably need to register a more specific preprocess function for each field, so you could have something like MYTHEME_preprocess_body(). From there you can get the whole node object and check to see if the transcript field is empty, and if so, add the class to the Body classes_array.

I'd be happy to work on this if you can hook up my Pantheon account (sean@proofstudio.net) to the repo. That should be possible right?

**Comment by jensimmons** [comment]
Update: I don't need this after all. At least not so far. I radically changed the layout of the episode page (for other reasons), and now a few CSS tricks will work to get the layout to work no matter which fields are empty. 

Thanks anyway. I'll reopen this if I end up needing it for some reason.
