### ISSUE TITLE
Links in the transcripts don't work

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#29]
Open a transcript. Scroll & read. Attempt to click on a link. No dice. 

Also, at times episode pages scroll side-to-side once the transcript is open. 

It seems the CSS and JS I'm using to handle the truncated-by-default, click-to-see-full-transcript functionality is not going to work. Needs to be redone.

**Comment by philgruneich** [comment]
As I tweeted about, there’s a `z-index: -1` that causes the issue in `.node-type-episode .transcript dl`. You can solve this issue with:

```
.transcript-expander {
    position: relative;
    z-index: 2;
}
```

Considering that you remove the z-index from `.node-type-episode .transcript dl`, nothing seems to break :dancer:

**Comment by jensimmons** [comment]
fixed.
