### ISSUE TITLE
WELCOME! Wanna help?

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#3]
Interested in helping to build the new website for The Web Ahead? I'd love to have you help. 

Right now we've got a bunch of content tasks — adding and improving content. All the episodes have been entered into the system, but the new site will have much more content on each episode than the 5by5 site does, including more guest and sponsor information, transcripts for each episode, and more. That's where you come in. 

Look through this list of tasks on GitHub to see what needs to be done: https://github.com/jensimmons/thewebahead/issues. I'll keep adding more to-dos. 

If you are interested, go to http://dev.thewebahead.net/user/register and make yourself an account. Once I approve you and give you the right superpowers, you'll be able to add and edit content. 

And then comment in this issue that you are interested in helping. I'll add you as a collaborator to this project so you can claim issues and will get notifications when issues are added or updated. (Oh, if you don't have a GitHub account yet, you can sign up at https://github.com. A free account is fine. And for now you won't actually need to use Git or grab any code for this project. I'm just using their tools to create list of issues — as a place to organize what needs to be done.)

THANKS! I'm excited to have a community help build the show into something bigger. I have a ton of ideas, and having help will make it more possible to do them sooner rather than later. 

I also plan to have some kind of listener membership sections in the future. Anyone who helps now will forever be a member. Plus, I hope it's interesting and perhaps even educational to watch how this Drupal website gets assembled and styled. AND I want to give all of you credit on the site, so be sure to fill out your account with your photo (and later once I build the functionality, links, bio, etc). 

The website is being built in Drupal, but you don't need to know anything Drupally to help. Content stuff is all click, cut and paste in a web interface. 

But if you _do_ know Drupal 7, let me know! Especially if you know stuff like how to build Views with arguments, or code custom Entities. (At the moment, I'm trying to figure out how best to architect multiple flavors of comments / comment-like-entities). Or if you have experience in setting up a modern audio player in D7. That's a big one. Bonus for Media module integration (or wisdom about _not_ doing Media module integration).

Later, we'll be getting into front-end development... so it won't all be content tasks. We are just starting with content.

**Comment by jensimmons** [comment]
Oh, and don't get all disappointed that the current version of http://dev.thewebahead.net/ looks crazy weird default-Drupally! This is not how it's going to look when we are done. Or work, interface-wise. This is just how it starts out, as any Drupal project does. We focus on content structure, functionality, and linking. Do we have the right pieces in the right places? What functionality needs to be added to get more content in the right places, linked to the other right content? 

I always feel like I'm carving a block of marble. The sculpture at the end doesn't look like a square block, but it sure starts out that way. We start with the raw materials, and then chip at them, bit by bit. It only starts to look like the real thing over time. Hopefully you'll see big changes happening quickly. Don't be surprised when you get there and everything is different than the last time you were there. Welcome to the dev server!

**Comment by fonorobert** [comment]
Hey Jen, I just registered :)

**Comment by jensimmons** [comment]
Hi Robert. I just activated your account. Welcome.

Hey — I've been to Budapest. Just for one night, sadly (traveling from Belgrade to NYC), but it struck me as a remarkable place.

**Comment by jensimmons** [comment]
By the way, so this doesn't look like empty-land, several people who've been working on transcripts for The Web Ahead are now joining this effort. There's a whole discussion in another issue in the transcript repo... anyway, they are here to help, too:
- Jenn Schlick
- Jason Neel
- Matt Sugihara

\o/

**Comment by fonorobert** [comment]
Thanks, it's great to be able to help. And do visit Budapest when you can, it's a great city :)

**Comment by jensimmons** [comment]
Sean Fitzpatrick just joined the group too.

**Comment by jensimmons** [comment]
And Phil Jones.

**Comment by joe-watkins** [comment]
Registered to help in any way I can :)

**Comment by arthurvr** [comment]
Do you still need help? Just singed up ;-) I'm not a drupal pro, but I would love to help with the content and the front-end stuff.

**Comment by jensimmons** [comment]
Hello! Yes, welcome. Actually I'm about to have a couple new tasks that involve going through all the shows and making adjustments.... I'll post issues on GitHub once I'm clear what's needed. Thanks!

**Comment by arthurvr** [comment]
Perfect!

**Comment by jensimmons** [comment]
Here's a new thing to do. 
https://github.com/jensimmons/thewebahead/issues/27
@arthurvr wanna help? 
And everyone else.
Let me know on that ticket if you have any questions!
