### ISSUE TITLE
Launching Next Week. Truly. 

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#32]
I wanted to update everyone and let you know my plan is to launch next week. It's getting close!

Episode 94 just came out this evening. Episode 95 is being edited right now — it's all about the new website. My plan is to finish the website this weekend (still so much to do!) and launch the website at the same time episode 95 comes out. Which means I want to have the transcript and all the info ready to go. And for the last 5+ episodes to also look really great.

If you want to surf around dev.thewebahead.net and let me know if you see broken things, that would be cool. Leave notes in this ticket, or open new tickets. You might want to wait until Sunday & give me a chance to fix more bugs. I still need to adjust the CSS for phone screens. And write pages like the About and Subscribe page. And possibly redesign the home page. Nothing much ;P

I want to thank all of you again for helping make this happen. Many of you have worked hard on content and on the site itself. Some of you have just been here, providing an audience — which just that makes it easier to turn an idea into reality. So thank you for whatever you've done.

**Comment by joe-watkins** [comment]
Congrats! I saw those tickets getting closed and know what that means :) I can offer some front-end/accessibility QA. What browsers are you wanting to support?

**Comment by jensimmons** [comment]
Ooo nice. Yea, I've done so very little cross-browser testing, shamefully. Let's support

The latest versions of:
Chrome desktop
Chrome on Android
Firefox
Safari desktop
iOS Safari
Opera mini
Opera mobile

And:
IE 10+

It would be nice to take a look at IE8 and 9 and see what's going on. Hopefully IE8 isn't a scrambled egg. I don't care about IE6 or 7.

Do take an accessibility spin as well. Again, I haven't been testing (bad developer bad), but I have been working hard to create quality HTML from Drupal, to pay attention to source order and markup details — so I'm hoping it's in great shape for accessibility. Having someone else test / take a look would be incredibly helpful. Perhaps you'll find something big that I've missed that isn't hard to fix. 

Thanks!
