### ISSUE TITLE
Reviews not wrapping in Safari.

### ISSUE THREAD

**Issue by alyssais** [jensimmons/thewebahead#34]
Hi Jen, not sure if you already know about this, but the reviews don't look right in Safari. They scroll all the way off the screen, creating a huge scrollbar for the entire page. Looks like a flex box issue?

![screen shot 2015-02-01 at 22 37 31](https://cloud.githubusercontent.com/assets/2768870/5994229/0aa779cc-aa63-11e4-9dbb-037ea7cb7944.png)

**Comment by jensimmons** [comment]
Yes! It's a mess. I guess that's what happens when I am trying to do too many things at once. I will get to this. And even better, figure out how to take the design of the layout up a notch (besides, er, making it fit!!)

Thanks Ross!

**Comment by jensimmons** [comment]
Fixed. Turns out I'd ut prefixed CSS in my code, to cover webkit and others — and I'm running Autoprefixer. The combination of two attempts to cover browsers that need a prefix ended up with no working code. Weird. Deleted my prefix & trusted the robots. Works great.

Thanks.
