### ISSUE TITLE
Mailchimp Drupal integration - signup form is dumb. Shortcut to better?

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#35]
The email newsletter system is Mailchimp. I set the Mailchimp module in Drupal. I'd hope it'd be cool. But the basic form is dumb. 

http://dev.thewebahead.net/newsletter/signup

The problem is that checkbox. There's only one choice at the moment (only one mailing list to "choose" from), but I don't see a way to make this form default to a set value & then not ask the question (preferred, & the behavior you can get from a normal Drupal field), or at least pre-check the box. 

I've looked at the settings a few times. And there doesn't seem to be any functionality for what I want. I'm assuming the module is like many Drupal modules, just not well thought through / not powerful enough to do good UX for a variety of usecases. 

My question really is, have any of you run into this? Do you happen to already know what I could do (quickly) to make this better? 

It's not a launch-blocker, so I'll ship with it like this if there's no quick fix. And dive deeper later.

**Comment by proko** [comment]
Hello Jen. I've run into this and the patch here solved the issue for now https://www.drupal.org/node/2368307

**Comment by jensimmons** [comment]
Excellent! Could not have been easier to fix. I installed the module, and done. The form doesn't have the checkbox.

http://monosnap.com/image/iviqFdJrzscPCst5GqDoEtRmR3pucG.png

THANKS!!
