### ISSUE TITLE
A super easy task! That's tedious & boring. And helpful!

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#36]
I just added an alt field and title field to the images for all the guest bios. I've edited four. The other 76 need to be done. 

Here's what to fill out:
http://monosnap.com/image/7bzgIdW0M4OzO9ERqh4IZ6KtTNwE3A.png

type:
**a photo of [Guest Name]**
into the alt field and
**[Guest Name]**
into the title field. 

Thanks!

**Comment by JasonNeel** [comment]
Forgive my Drupal ignorance, but would you be able to utilize already existing fields for this in your template? You do already have the details you need in the first and last name fields (and I'm guessing the title field of your Guest entry). It would keep things a little more DRY.
