### ISSUE TITLE
Upload all the sound files

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#5]
This one is easy, tedious, and slow. Having an internet connection with fast upload speeds will help. 

\o/

There's a field on each episode for saving the sound file. 

![edit episode advanced accessibility with derek featherstone the web ahead 2014-08-05 21-02-34 2014-08-05 21-02-35](https://cloud.githubusercontent.com/assets/108474/3821153/0a615450-1d06-11e4-92fd-97c8f3a3b41f.jpg)

Most of these are currently empty.

Your mission: upload all the files.

Here's How:

1) Download all the shows — iTunes is an easy place to do this. All the files will end up on your hard drive in the iTunes library. Or, you know, if you don't do iTunes, cool. Grab the files however you wish.

![the web ahead 2014-08-05 21-14-57 2014-08-05 21-15-12](https://cloud.githubusercontent.com/assets/108474/3821190/23dae01c-1d07-11e4-867e-f150f72cbf95.jpg)

2) Go to http://dev-webahead.gotpantheon.com/episodes/needs-sound-file to see a list of all episodes that still need their sound files. 

3) Choose an episode and click edit. (You have to be logged in to see the edit links.)

4) Under the Sound File field, click "Choose file" and point to the file on your computer. Then Click "Upload the file". Then BE VERY VERY PATIENT. It will take a while for the file to upload. 

5) After the file looks happy and done, THEN click save (at the very bottom of the form). That should work. Double check to see if it does work the first few times you do this. (You can find episodes that are now _not_ on the "Needs Sound Files" list at: http://dev-webahead.gotpantheon.com/admin/workbench/content/all?title=&type=episode&published=1&items_per_page=100 )

**Comment by jensimmons** [comment]
I see you chomping through these! Fabulous :)

**Comment by fonorobert** [comment]
I don't have much experience with Drupal but I wanted to start doing something, so I think I'll be through by tomorrow afternoon. Also found some older episodes I haven't listened to yet :)

**Comment by fonorobert** [comment]
Done :)

**Comment by jensimmons** [comment]
Excellent!! Thanks so much. :)

**Comment by jensimmons** [comment]
Check it out! NOTHING needs sound files. Yummy.

![shows that need sound files the web ahead 2014-08-07 14-57-19 2014-08-07 14-57-23](https://cloud.githubusercontent.com/assets/108474/3847351/ba70de7e-1e64-11e4-80cd-0889bc596d25.jpg)
