### ISSUE TITLE
Add the sponsors

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/thewebahead#9]
So in this new system, there will be a page for each sponsor — much like we have a page for each guest. 

We need to start by adding the sponsors as new content. One time for each sponsor. 

You can find sponsor information on each episode. Create the sponsor. Copy and paste whatever information you can find. I'll go into the scripts for the sponsor reads later, and put more information into the system. 

It would be incredibly awesome if you can go hunt down a log for each sponsor — from their website or wherever else on the web logos might be roaming. 

BTW, Environment for Humans sponsored a bunch of shows, promoting a whole bunch of different conferences. I think we should just have one page for them, and then promote all the conferences on that one page — instead of creating separate sponsor nodes for each conference. I started such a thing here: http://dev-webahead.gotpantheon.com/sponsor/environments-humans

And I started another sponor: http://dev-webahead.gotpantheon.com/sponsor/event-apart 

Much work to be done on this — to figure out the details. I'm not convinced that the content type "sponsor" has the right fields yet. Please drop comments here, and we can discuss and improve.

**Comment by jensimmons** [comment]
Let's start this with the most recent episode — 77 — and work our way back. That way if we only get 2014 done, that'll be fine. The older sponsors can wait.

**Comment by jensimmons** [comment]
And while you in there looking at the sponsor info on each episode, remove the paragraph markup. (`<p>sponsor text</p>`). Drupal doesn't need the `<p>`s.

**Comment by alyssais** [comment]
@jensimmons Edited your comment to escape the HTML, because GitHub wasn't displaying it properly.

**Comment by jensimmons** [comment]
Ah. ha. thanks!

**Comment by sffitzpatrick** [comment]
I just did 77-74: Lynda, Media Temple, and O'Reilly. I treated O'Reilly as the primary sponsor with the conference itself as a link (like Environments)

A question and an observation:
-  Did you intended to make 500x500 the _minimum_ dimensions for logo images or should that be max? I don't know how you'll eventually use the images so maybe that was an intentional min size.
-  Also a quick thought on the link field -- maybe in addition to that field it would be handy to have another link field for the sponsor's primary homepage or offer URL or something. Just another field with ONE value to be used for theming later on. So you could link the logo, etc, to a particular URL. Again, though, I'm not exactly sure how you'll be using these so maybe I'm overthinking it.

**Comment by jensimmons** [comment]
No, I didn't intend for the minimum size for logos to be 500x500. That carried over from when I first created this field for guest bios. Good catch. I just reduced that requirement to 200x100. I want all image to be as big as possible... especially for retina screens, etc, etc. But it's going to be tricky to find big logos for many sponsors, I expect. Especially the backlog. Let me know if 200x100 is still too restrictive. 

As for the link field, it was one link when I first built this out. Again, it being a shared field, it got switched to four later, unintentionally. Hm. I'm not sure we ever need more than one link, honestly. I think I'll go make a new field (that's not shared) and replace the four-link field. 

You aren't overthinking it. You are on the mark. Thanks!! It's truly helpful to have other eyes on these kinds of things.

**Comment by sffitzpatrick** [comment]
Just added down through Ep 60. It goes fast because of the repetition. Also I'm having pretty good luck finding good quality logos on the sponsors' "Press Center" pages on their sites.

I'm just trying to stay faithful to what's on the current 5by5 site, but I'll bet some of the sponsors will chime in with more complete "description" text now that they're getting a dedicated page.

**Comment by jensimmons** [comment]
It working well to make sure every logo has a white (or clear) background. 

A google image search also does a pretty good job of quickly finding guests pictures & sponsor logos. Narrowing the search to "large" images can hope too. 

Yes, just copy and paste what's on 5by5, or what's on the corresponding episode page on the new page site (which was scraped from 5by5 using Feeds). I will go through all the sponsor pages later and add the info I have from the original reads / original emails with the sponsor about what they wanted. 

So don't worry that the sponsor pages have great content. It's more of a help to just get the pages to exist, with a good logo, and to be linked up with the right episodes. I'l take care of the rest. 

And we might need to tweak the fields. I'm wondering... since the coupon codes change sometimes, or there's more than one link.... I'm open to adjusting the content type once we see what the actually content needs are. It doesn't seem quite right yet.

**Comment by jensimmons** [comment]
I temporarily added sponsorship info the to main list of episodes at http://dev-webahead.gotpantheon.com/episodes. This should make going through sponsors easier / faster.

**Comment by jensimmons** [comment]
<strike>DO NOT DO any of the sponsors for episodes 1-17. I don't think that information is correct. I'll figure it out — but meanwhile, leave those shows alone. No sense in entering a bunch of data that has to be later deleted.</strike> 

UPDATE: I straightened everything out. The sponsors are all correct now.

**Comment by jensimmons** [comment]
You know what team, I _do_ want to go back into 2011-2013 and add a page for every sponsor. We've got 2014 done (thanks!). 

I've put all the sponsor info on: http://dev.thewebahead.net/episodes to make things faster. I've also created this totally temporary page that shows everything for each sponsor on one page: http://dev.thewebahead.net/sponsors-temp, also to make things faster. 

I think there are about 16 more companies to add, plus a lot of info to add to the Environments for Human page. 

I'll be working on this myself as well....

**Comment by jensimmons** [comment]
Alrighty! All the sponsors have been added, and every sponsor is hooked up to the right episodes. Zeesh! Lots of info. 

I've removed adding & editing capabilities for Team Web Ahead to access sponsor stuff since this is finally all set. There's nothing more to do, and I don't want what's there to get messed up by accident. 

Thanks everyone!!
